# Generated by Django 3.0 on 2019-12-17 09:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_auto_20191217_1500'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='about',
            field=models.TextField(default=django.utils.timezone.now, verbose_name='About you'),
            preserve_default=False,
        ),
    ]
